### ISSUE TITLE
Missing Google_Service_Directory classes

### ISSUE THREAD

**Issue by davaxi** [google/google-api-php-client-services#1]
Hello,

I'm trying to get my server application to manage Google App Domain Calendars resource's but missing class Google_Service_Directory in v2 of google-api-php-client. 

Missing migrate this file https://github.com/google/google-api-php-client/blob/v1-master/src/Google/Service/Directory.php in this repositories.

Thanks

Duplicated with https://github.com/google/google-api-php-client/issues/911

**Comment by bshaffer** [comment]
This was not added to this repo because it is not a supported api (see the [api explorer](https://developers.google.com/apis-explorer/#p/) for a list of supported apis)

**Comment by davaxi** [comment]
It's not supported in v2 ? because i found services : https://developers.google.com/apis-explorer/#search/directory/admin/directory_v1/

**Comment by simonflore** [comment]
Hey @bshaffer This is still mentioned in the API Explorer. I see no reason why this wouldn't be included. https://developers.google.com/apis-explorer/#search/directory/m/admin/directory_v1/directory.resources.calendars.delete

**Comment by bshaffer** [comment]
added in #11
