### ISSUE TITLE
Incorrect documentation in people.peopleconnections

### ISSUE THREAD

**Issue by tristansokol** [google/google-api-php-client-services#101]
I was looking for documentation on the people API after running the [Quickstart](https://developers.google.com/people/quickstart/php) and foud my way to: https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/People/Resource/PeopleConnections.php

That wasn't very helpful because the information there seems to be wrong. Page size actually goes up to 2000 not `@opt_param int pageSize The number of connections to include in the response.
    Valid values are between 1 and 500, inclusive. Defaults to 100.`. And the `personFields` optional parameter doesn't seem to be documented at all, yet is used in the Quickstart

**Comment by mattwhisenhunt** [comment]
That is a great point, in fact, all the code in this repository is auto-generated and some times it shows. I use either [API Explorer](https://developers.google.com/apis-explorer/#p/people/v1/) or the API's [reference page](https://developers.google.com/people/api/rest/) as the source of truth when I am looking for info on a particular API.
