### ISSUE TITLE
How i can use importRows in my project?

### ISSUE THREAD

**Issue by MarceloBonifazio** [google/google-api-php-client-services#105]
I have this code:

		$out = fopen('php://output', 'w');
		fputcsv($out, 
			array('Location')
		);
		foreach($objects as $object){
			fputcsv($out, 
				array(
					$ad->objectLat.",".$ad->objectLnt,
				)
			);
		}
		$test = fclose($out);
		
		$client = new Google_Client();
		$client->useApplicationDefaultCredentials();
		$client->setScopes('https://www.googleapis.com/auth/fusiontables');
		$service = new Google_Service_Fusiontables($client);
		$service->table->importRows($test);

I looked in the documentation, but could not find the reference

**Comment by mattwhisenhunt** [comment]
Dupilcate of https://github.com/google/google-api-php-client/issues/1388
