### ISSUE TITLE
Service Account with Adsense?

### ISSUE THREAD

**Issue by timothymarois** [google/google-api-php-client-services#106]
I have spent the last few days trying to work with these crap PHP APIs for connecting Google services, and so far have gotten nowhere. Can you use a service account for Adsense access? Or must it always be OAuth?

**Comment by mattwhisenhunt** [comment]
That is a good question. There is actually an open issue to address the fact that it is not explicitly clear which APIs do not support service accounts. From what I can see there is no mention of service accounts in the [AdSense documentation](https://www.google.com/search?q=%22service+account%22+site%3Adevelopers.google.com%2Fadsense%2F&oq=%22service+account%22+site%3Adevelopers.google.com%2Fadsense%2F).

Please let me know where you got that impression so I can make sure it is updated.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
