### ISSUE TITLE
[Question] Get metadata only of a file using id

### ISSUE THREAD

**Issue by kocoten1992** [google/google-api-php-client-services#111]
I want to get metadata only of a file using id, we have this code, but it take both metadata AND the file (not what I want)

https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Drive/Resource/Files.php#L147

My ultimately goal is, I want to implement something like resumable download using file id, it will download chunk of file each time (like 5mb).

I don't know if we have that kind of function yet (please show me).

If we don't have it yet, I would like to know bytes length of file, then I could implement it myself.

Thank you !

**Comment by mattwhisenhunt** [comment]
You can tell get what metadata you want in the fields parameter.
https://developers.google.com/drive/v3/reference/files/get
https://developers.google.com/drive/v3/reference/files#resource
https://developers.google.com/apis-explorer/#p/drive/v3/drive.files.get (_Use fields editor_ is a handy way to choose your fields)

**Comment by kocoten1992** [comment]
@mattwhisenhunt :100: 

From your thirds link, I've figure it out, something like this:

$googleDrive->getService()->files->get('2-CzzKsomerandomidwanv_nd2hcJotl', ['fields' => 'id,size'])

Thank you!
