### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by JURALOVE** [google/google-api-php-client-services#112]
Hello!

I wondered if someone has made a method drag & drop to send or bring files to Google Drive.

Thank you for your ideas.

**Comment by mattwhisenhunt** [comment]
I am not aware of any for PHP. It sounds like Javascript would be the best fit for that. (Our nodejs libraries, like PHP, are server side and not exactly what you are looking for.)

You would probably want to link up a Drag & Drop browser js library with the [upload method](https://developers.google.com/drive/v3/reference/files/create?apix=true). (Make sure to select the Javascript material tab.)

**Comment by JURALOVE** [comment]
Thank You, Matt. I'll investigate where you have told me. Great work!
