### ISSUE TITLE
Is there a built-in way of making asynchronous requests?

### ISSUE THREAD

**Issue by NinoSkopac** [google/google-api-php-client-services#113]
👋 

Is there a built-in way of issuing multiple concurrent requests (specifically, for TTS)?
My use case is as follows: I want to use TTS to convert text into audio, but since it's a long string I'd like to split it up into chunks of 5000 chars each and convert them concurrently (in order to save time). 

In AWS' SDK, I use `CommandPool`, which makes this very easy ([example](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/commands.html#commandpool)). 

Furrhermore, AWS' SDK will also retry any failed attempts, so all I had to do to implement AWS Polly (their version of TTS) is as follows:

```php
    public function synthesize() : SynthesisInterface {
        $config = Config::getPollyConfig();
        $config += ['retries' => 1000];
        $polly = new PollyClient($config);

        $commandGenerator = function(array $chunks) use ($polly) {
            foreach ($chunks as $chunk) {
                yield $polly->getCommand('SynthesizeSpeech', [
                    'OutputFormat' => Config::Output_Format,
                    'Text' => $chunk,
                    'TextType' => 'text',
                    'VoiceId' => $this->voiceId
                ]);
            }
        };

        $commands = $commandGenerator($this->getTextChunks());
        $pool = new CommandPool($polly, $commands, [
            'concurrency' => 80,
            'fulfilled' => $this->getPollyFulfilledFn(),
            'rejected' => $this->getPollyRejectedFn()
        ]);

        $promise = $pool->promise();
        $promise->wait();
        ksort($this->audio);

        return $this;
    }
```

Can I do this with your SDK?

**Comment by mattwhisenhunt** [comment]
Check out the GCP client for all the latest bells and whistles: https://github.com/GoogleCloudPlatform/google-cloud-php#google-cloud-translation-ga
