### ISSUE TITLE
Uploading Screenshots

### ISSUE THREAD

**Issue by hablema** [google/google-api-php-client-services#124]
How can I upload screenshots using the api ? I'm able to change the store listing but not able to upload the screenshots.

**Comment by mattwhisenhunt** [comment]
```php
$service = new Google_Service_AndroidPublisher($client);
$service->edits_images->upload(...)
```

https://developers.google.com/android-publisher/api-ref/edits/images/upload
https://github.com/google/google-api-php-client#examples

**Comment by hablema** [comment]
Thanks @mattwhisenhunt , it worked!
