### ISSUE TITLE
Ability to handle merchant center promotion feeds through the api

### ISSUE THREAD

**Issue by r4ndsen** [google/google-api-php-client-services#128]
Hello, 
We're looking for a way to manage promotion feeds through the content api.
However currently they are not accessible through the regular datafeeds endpoint [Datafeeds.php](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/ShoppingContent/Resource/Datafeeds.php#L125)

Also there is no other resource that handles them.

Is there a way for us to automate promotion feeds at all without manually logging into each sub-account?

thank you

**Comment by mattwhisenhunt** [comment]
This library is generated code for all APIs as such we don't have a lot of answers when it comes to specific API questions. Looks like https://groups.google.com/forum/#!forum/google-content-api-for-shopping is the right place for these questions.

**Comment by r4ndsen** [comment]
appreciate it, thank you
