### ISSUE TITLE
Support CloudMonitoring v3 since v2 has been deprecated. 

### ISSUE THREAD

**Issue by shinfan** [google/google-api-php-client-services#18]
Based on the cloud API reference:
https://cloud.google.com/monitoring/docs/apis

**Comment by bshaffer** [comment]
@shinfan according to the [Discovery APIs](https://disc-prox.appspot.com/), `v2beta2` is the current version. Because these files are generated from the Discovery API, we can't update to v3 until it happens in discovery.
