### ISSUE TITLE
Support for sites

### ISSUE THREAD

**Issue by smalot** [google/google-api-php-client-services#19]
I can't find any services about Google Sites support.
May I forgot something ?

**Comment by bshaffer** [comment]
Unfortunately, this API is *not* directly supported by this client library (yet). However, you can use this library for  [authentication](https://developers.google.com/google-apps/sites/docs/1.0/developers_guide_protocol), and then create a guzzle HTTP request. This would look something like:

```php
$client = new Google_Client;
$client->addScope('https://sites.google.com/feeds/');
$client->setAccessToken($accessToken);

// make the call
$http = $client->getHttpClient();
$request = new GuzzleHttp\Psr7\Request('GET', 'https://sites.google.com/feeds/activity/domainName/siteName');
$response = $http->send($request);

// decode the JSON response
$activityFeed = json_decode((string) $response->getBody(), true);
```

**Comment by smalot** [comment]
Thanks for your feedback.

Is it scheduled to add site support ?
Where can I found a full documentation of the Sites API ?
