### ISSUE TITLE
Is there a way to get Android APKs testing mode?

### ISSUE THREAD

**Issue by khrizt** [google/google-api-php-client-services#2]
I am currently getting the list of published Android APK versions through the Google_Service_AndroidPublisher service but there's no way, at least I haven't found it, to know if each of those APKs in the list is in alpha or beta testing mode or filter only production APKs.

Is it possible somehow? If not, can be added somehow? I've seen there is an optional params argument in the method but there's no documentation at all about them :)

**Comment by bshaffer** [comment]
This repository is not meant for requests to the APIs themselves, only the generated code for the APIs. Looking through the Android Publisher API, it seems like the [tracks.get](https://developers.google.com/apis-explorer/#search/apk/m/androidpublisher/v2/androidpublisher.edits.tracks.get) method will return all APKs assigned to a track for a specific package name. Maybe this is what you want.
