### ISSUE TITLE
'return' is used as a function name and cannot pass syntax check in php 5.5.30.

### ISSUE THREAD

**Issue by repeat** [google/google-api-php-client-services#21]
I'm using [google-api-php-client](https://github.com/google/google-api-php-client) on my project, and composer installs `dev-master` of this repository.

I check all codes from composer to assert everything works by using `php -l`, however it raised a sytnax error which indicates `return` is used as a funciton name:
`PHP Parse error:  syntax error, unexpected 'return' (T_RETURN), expecting identifier (T_STRING) in ./vendor/google/apiclient-services/Google/Service/Classroom/Resource/CoursesCourseWorkStudentSubmissions.php on line 205`
```php
public function return($courseId, $courseWorkId, $id, Google_Service_Classroom_ReturnStudentSubmissionRequest $postBody, $optParams = array())
```

I'm using php 5.5.30 and it satisfies the minimum-required php version of google-api-php-client.

**Comment by bshaffer** [comment]
Thank you for reporting this! I'll get this fixed ASAP.
