### ISSUE TITLE
Google_Service_Gmail - Updates

### ISSUE THREAD

**Issue by carloshenriqueds** [google/google-api-php-client-services#26]
Guys.

Google documentation has been updated and added new classes, one of them is UserSettings.sendas, using the php this service'm having the following result:

Message: Undefined property: Google_Service_Gmail :: $ users_settings_sendAs
Message: Undefined property: Google_Service_Gmail :: $ users_settings_forwardingAddresses

Can anyone help me?Thanks..
[Gmail API](https://developers.google.com/gmail/api/v1/reference/users/settings/filters)

**Comment by bshaffer** [comment]
These properties now exist:

[sendAs](https://github.com/google/google-api-php-client-services/blob/master/Gmail.php#L70)
[forwardingAddresses](https://github.com/google/google-api-php-client-services/blob/master/Gmail.php#L69)

**Comment by carloshenriqueds** [comment]
Yes! These properties now exist!

but I was using and does not work
