### ISSUE TITLE
Not Found Google_Service_BatchAnnotateImagesResponse classes

### ISSUE THREAD

**Issue by pakotan** [google/google-api-php-client-services#3]
Please excuse my poor English.

I use Vision API.
But my IDE have some warning.

```
$service = new \Google_Service_Vision($client);
$result = $service->images->annotate($body);
// Method 'getResponses' not found in \Google_Service_BatchAnnotateImagesResponse
$response = $result->getResponses();
```

ImageResource.php
annotete function
```
  /**
   * Run image detection and annotation for a batch of images. (images.annotate)
   *
   * @param Google_BatchAnnotateImagesRequest $postBody
   * @param array $optParams Optional parameters.
   * @return Google_Service_BatchAnnotateImagesResponse
   */
  public function annotate(Google_Service_Vision_BatchAnnotateImagesRequest $postBody, $optParams = array())
  {
    $params = array('postBody' => $postBody);
    $params = array_merge($params, $optParams);
    return $this->call('annotate', array($params), "Google_Service_Vision_BatchAnnotateImagesResponse");
  }
```

param and return use Google_BatchAnnotateImagesRequest.
But Google_BatchAnnotateImagesRequest can not be found anywhere.
I think, this comment is Google_Service_Vision_BatchAnnotateImagesRequest and Google_Service_Vision_BatchAnnotateImagesResponse.
Or do i mistake how to use the api?

**Comment by bshaffer** [comment]
There is an annotation error in [ImagesResources](https://github.com/google/google-api-php-client-services/blob/master/Vision/ImagesResource.php#L33) that is casing this warning. I will look into a fix. Thank you for finding this!
