### ISSUE TITLE
Storage: Add ability to generate signed URLs for download and resumable uploads

### ISSUE THREAD

**Issue by chrispappas** [google/google-api-php-client-services#33]
Currently I don't see any way to easily use the API to generate a signed URL for a given object in a bucket, and have to write my own code to do so. This wasn't a problem and I have a working solution now.

It would be preferable to have a simple method to supply the bucket and file name, along with the expiry time and other signature info and receive a signed URL using the json cert.

A bigger roadblock now is being able to generate a [resumable upload signed URL](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload) using the library. Because the prefix for the initial POST request is `/upload/storage/...` there's no support that I've been able to see in the current PHP sdk.

I apologize in advance if I've just missed something but I've searched the documentation and repo for the last couple of days trying to find a solution without any luck. Thanks in advance!

**Comment by mattwhisenhunt** [comment]
@chrispappas Have you, by chance, seen the new [client libraries](https://cloud.google.com/storage/docs/reference/libraries)? It sounds like you are (were at the time) writing new code and they might fulfill your needs better.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
