### ISSUE TITLE
Duplicate file from autogeneration - with different cases

### ISSUE THREAD

**Issue by thejaswip** [google/google-api-php-client-services#34]
google-api-php-client-services/src/Google/Service/Compute/HTTPSHealthCheck.php should be deleted

as google-api-php-client-services/src/Google/Service/Compute/HttpsHealthCheck.php this what we need 

Note the "case" of file names, especially in windows based system this will lead to issue where the one with CAPS will most likely overwrite the other !

**Comment by thejaswip** [comment]
similarly HTTPHealthCheck.php should be deleted keeping HttpHealthCheck.php

**Comment by touhonoob** [comment]
got the same issue

**Comment by demotascha** [comment]
`HTTPHealthCheck.php` => `HttpHealthCheck.php`
`HTTPSHealthCheck.php` => `HttpsHealthCheck.php`

**Comment by demotascha** [comment]
fixed #39
