### ISSUE TITLE
Google Speech API Key

### ISSUE THREAD

**Issue by gustavo4** [google/google-api-php-client-services#36]
Hi 

I want know where I must put the API key? 

I have this error:
Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information

I share my code. Thanks 

            $speech = new SpeechClient([
                'projectId' => 'PROJECT_ID'
            ]);

            $recognizeOptions = [
                'encoding' => 'LINEAR16',
                'languageCode' => 'fr-FR',
                'sampleRate' => 16000,
            ];

           // Recognize the speech in an audio file.
            $results = $speech->recognize(
                fopen(__DIR__ . $pathUploads.'/'.$fileAudio, 'r'),
                $recognizeOptions
            );

**Comment by mattwhisenhunt** [comment]
You may want to take a look at these [newer GCP client libraries](https://github.com/GoogleCloudPlatform/google-cloud-php).
