### ISSUE TITLE
New endpoint for BATCH requests (translation api)

### ISSUE THREAD

**Issue by infinitely-young** [google/google-api-php-client-services#47]
Need to fix endpoint for translation API. I have received this message to my email:

Our records indicate that your team haas occasionally used the the HTTP batch mode to request Translation API service by making a POST request to https://www.googleapis.com/batch (details here). We have a pending change in February that will discard batch requests to translation service using the above method. We have an alternative way for you to continue to use the batch functionality: instead of using the https://www.googleapis.com/batch endpoint to make batch requests, please use the endpoint https://translation.googleapis.com/batch/translate to get the same functionality. We request you to make this change as soon as you can. Please reach out to use in case you have any questions. 

Google Cloud Support

**Comment by mattwhisenhunt** [comment]
Did you get migrated to the new API okay?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
