### ISSUE TITLE
Duplicate filenames

### ISSUE THREAD

**Issue by c960657** [google/google-api-php-client-services#48]
2 x 2 filenames in `src/Google/Service/Compute` are identical except for case:

```
HTTPHealthCheck.php
HttpHealthCheck.php

HTTPSHealthCheck.php
HttpsHealthCheck.php
```

A fix was attempted in #39, but the files have reappeared in adfe1f5f2bbd79fd18b5b5caab69017c7400c727.

It seems both class names are defined by the API:
https://www.googleapis.com/discovery/v1/apis/compute/alpha/rest

**Comment by bshaffer** [comment]
fixed in #51
