### ISSUE TITLE
How to access Admin SDK since 2.0?

### ISSUE THREAD

**Issue by stteads** [google/google-api-php-client-services#5]
Hi,

I didn't found how to manage users from a Google Apps domain since 2.0? (I use Google_Service_Directory->users->listUsers() in 1.0?)

Full doc : https://developers.google.com/admin-sdk/
API still accessible : https://console.developers.google.com/apis/api/admin/overview and not marked as deprecated

**Comment by gplaza** [comment]
Same question here

**Comment by bshaffer** [comment]
added in #11
