### ISSUE TITLE
Non-conformant response from Google CSE API

### ISSUE THREAD

**Issue by fernando-almeida** [google/google-api-php-client-services#54]
Hi guys,

I've been trying to make use of the Google CSE resources and I think I've encountered I bug related with one of your server responses.
The JSON response being returned from a call to the resource [Google_Service_Customsearch_Resource_Cse](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Customsearch/Resource/Cse.php)::listCse does not comply with the specification mentioned in the [documentation](https://developers.google.com/custom-search/json-api/v1/reference/cse/list#response).
Each named key per query is supposedly meant to hold an array and not an array with a single element (see index 0 below). This breaks your decoding approach for the JSON data that should get mapped to the [Google_Service_Customsearch_Query](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Customsearch/Query.php) class.

The easiest way I found to reproduce this response was to remove the final modifier from [Google_Model](https://github.com/google/google-api-php-client/blob/master/src/Google/Model.php)::__construct followed by the creation of a [Google_Service_Customsearch_Search](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Customsearch/Search.php)::__construct in which I dump the contents of the value that is passed to this constructor.

Without access to these instances of Google_Service_Customsearch_Query I would have to keep track of the last query parameters/results and also run my own math to proceed with next page requests.

Below is a partial output of the received JSON response:
```
Array
(
    [kind] => customsearch#search
    [url] => Array
        (
            [type] => application/json
            [template] => '...'
        )
    [queries] => Array (
            [request] => Array  (
                    [0] => Array  (
                            [title] => Google Custom Search -
                            [totalResults] => 2030000000
                            [searchTerms] => '...'
                            [count] => 10
                            [startIndex] => 1
                            [inputEncoding] => utf8
                            [outputEncoding] => utf8
                            [safe] => off
                            [cx] => '...'
                        )
                )
            [nextPage] => Array (
                    [0] => Array  (
                            [title] => Google Custom Search 
                            [totalResults] => 2030000000
                            [searchTerms] => '...'
                            [count] => 10
                            [startIndex] => 11
                            [inputEncoding] => utf8
                            [outputEncoding] => utf8
                            [safe] => off
                            [cx] => '...'
                        )
                )
        )
...
)
```

Keep up the good work.

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to re-open this issue and explain why you believe fixing it is essential for users of this client library.

**Comment by arekm** [comment]
We just hit it, too, found this issue and now checking date if it is 1 april but no... it's not.

Is fixing it hard or problematic in any way? It's essential because people simply hit it.
