### ISSUE TITLE
Missing Resumable Upload 

### ISSUE THREAD

**Issue by Joe-brainlabs** [google/google-api-php-client-services#55]
Currently the Gmail client uses multipart upload, which is capped at 5MB. 
Is there a way to use it to do resumable uploads for larger files?

**Comment by phil-brainlabs** [comment]
@Joe-brainlabs No, typically we [zip](http://php.net/manual/en/class.ziparchive.php) to get around this.

**Comment by mattwhisenhunt** [comment]
It looks like your best bet is to [upload to Google Drive](https://developers.google.com/drive/v3/web/resumable-upload) and send an email with a link to the new file.
