### ISSUE TITLE
Add an example of using the BigQuery client API with query parameters

### ISSUE THREAD

**Issue by ElliottBrossard** [google/google-api-php-client-services#56]
The BigQuery documentation includes [examples for Python and Java](https://cloud.google.com/bigquery/querying-data#running_parameterized_queries) but not for PHP. A user asked a question about [query parameters with PHP on StackOverflow](http://stackoverflow.com/questions/42677989/google-bigquery-running-parameterized-queries-php), but there aren't any working samples.

**Comment by mattwhisenhunt** [comment]
Thanks for opening this issue. It looks like it has been resolved.
