### ISSUE TITLE
Customsearch needs an update to v2

### ISSUE THREAD

**Issue by dkuss** [google/google-api-php-client-services#58]
Customsearch needs an update to API v2.

I just got the following email from Google as a warning:
"The Custom Search Element API 1.0, which was deprecated in 2012 in favor of API 2.0, is now no longer maintained. API 1.0 may experience outages and failures, and **possibly stop working entirely**."

**Comment by saicheems** [comment]
I believe that's a different library? `customsearch` doesn't currently have a `v2` listed.
