### ISSUE TITLE
Override the rootUrl when constructing a Google_Service_Pubsub for Pubsub Emulator

### ISSUE THREAD

**Issue by mc0** [google/google-api-php-client-services#59]
Our team has hit a roadblock with using the pubsub emulator project alongside this API. It looks like we're unable to override the rootUrl and, as a result, we can't really use them together in our development environment.

I'd be open to submitting code to correct this issue but I'd like some advice on the best approach. Our team thinks that being able to provide it to the Google_Client constructor would let each Service to inherit the rootUrl, if defined, and not wind up being a ton of changes.

Is there any path forward for fixing this?

**Comment by mc0** [comment]
@bshaffer Hey, I've seen you active and while I know this isn't the biggest "problem," it makes it really tough from a developer perspective. Would you mind giving it a look?

**Comment by mattwhisenhunt** [comment]
Please provide more detail about what error you are getting. A small snippet of code that reproduces the error would be very helpful.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
