### ISSUE TITLE
Google People API - Deprecated method parameter "requestMask.includeField"

### ISSUE THREAD

**Issue by sayhitovincent** [google/google-api-php-client-services#67]
Hey guys, are we able to replace the "requestMask.includeField" parameter with "personFields"? It's now documented within the Google People API that the former parameter is now deprecated. 

File: https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/People.php#L146
Line: 146
Documentation: https://developers.google.com/people/api/rest/v1/people.connections/list

**Comment by aaronhuisinga** [comment]
I just stumbled upon this exact same issue. It is definitely not working in the current release version.

**Comment by aaronhuisinga** [comment]
Lines 92 and 101 also need to have the same change made. I'll open a PR.

**Comment by sayhitovincent** [comment]
You'll also find that `Google_Service_People_ListConnectionsResponse` is missing getters/setters to totalPeople and totalItems. Can I get a second confirmation that this true for others?

**Comment by saicheems** [comment]
It looks like the owners of the people:v1 service have renamed their API from "People" to "People Service", which means updates to the service are happening here:

https://github.com/google/google-api-php-client-services/tree/master/src/Google/Service/PeopleService

Is it possible for you to switch your client initialization code from new Google_Service_People() to new Google_Service_PeopleService()? That'll get you the updated fields.
