### ISSUE TITLE
Two identical files BigQueryDataTransfer.php / BIGQUERYDATATRANSFER.php

### ISSUE THREAD

**Issue by sod** [google/google-api-php-client-services#73]
My composer complains about two identical files it can't create - composer 1.4.2 / HPFS+ / macOS sierra / case insensitive :/

```bash
composer require google/apiclient-services v0.14
```
```log
  - Installing google/apiclient-services (v0.14): Loading from cache
    Failed to execute unzip -qq  '/Users/x/dev/playground/google-apiclient/vendor/google/apiclient-services/031c183dc14ccce7d7407e0e574c41a0' -d '/Users/x/dev/playground/google-apiclient/vendor/composer/340ef576'

replace /Users/x/dev/playground/google-apiclient/vendor/composer/340ef576/google-google-api-php-client-services-b8c3ee8/src/Google/Service/BigQueryDataTransfer.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```

In particular, these:

[src/Google/Service](https://github.com/google/google-api-php-client-services/tree/master/src/Google/Service)
[src/Google/Service/BIGQUERYDATATRANSFER.php 10.1 kb](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/BIGQUERYDATATRANSFER.php)
[src/Google/Service/BigQueryDataTransfer.php 19.1 kb](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/BigQueryDataTransfer.php)

![image](https://user-images.githubusercontent.com/905328/28279528-0b309cb2-6b21-11e7-98de-50f67a101356.png)

**Comment by bshaffer** [comment]
Fixed in `v0.15`

**Comment by tacovandenbroek** [comment]
This issue doesn't seem fixed at all. In both [v0.15](https://github.com/google/google-api-php-client-services/tree/v0.15/src/Google/Service) and [master](https://github.com/google/google-api-php-client-services/tree/master/src/Google/Service) these two files exist. On case sensitive filesystems this is not a problem, but on case insensitive filesystems this causes fatal errors and checkout issues.

**Comment by Sneakr** [comment]
+1

**Comment by Sneakr** [comment]
+1 This is not solved.

**Comment by klausbreyer** [comment]
+1 have this in v0.21

**Comment by saicheems** [comment]
Properly fixed this time, in `v0.24`.

**Comment by vibrantBits** [comment]
Here with v0.37, got the fatal error in Windows.

**Comment by NoiseEee** [comment]
So weird, I've tried to "composer install" google/apiclient-services on the Linux VM within four windows machines; all but one are fine, same version of composer, same version of apiclient-services.... and the same error as listed here. What could be the issue??
