### ISSUE TITLE
Finer control over dependencies

### ISSUE THREAD

**Issue by brstgt** [google/google-api-php-client-services#74]
As long as I use composer, I have to include _ALL_ services if I only want to access a single service.
This is a _MASSIVE_ overkill.
Why don't you create composer deps/packages for each service and maybe a target to include all services for backward compat?

It really sucks to add thousands (5097 !!) of files for a super simple API query.

**Comment by janhartigan** [comment]
This is seriously an embarrassing reality of this repository. Google libraries are usually pretty terrible, tho, so it's not super surprising.

**Comment by bshaffer** [comment]
Thank you for voicing your opinions here. I fully agree.

Because Composer requires a repository per package, we'd have to maintain 140+ repositories to allow for each service to be used individually. This is actually not a big deal IMHO, it could be automated and would be well worth the investment ford what we'd gain in usability. But the extra overhead and is why this hasn't been done yet.

**Comment by janhartigan** [comment]
@bshaffer you could also look into subtree splits. Considering the number of repositories, it may prove unwieldy, but that way you get a repository per package, but you only have to maintain the main monolithic repo. Laravel does this where the main package is [laravel/framework](https://github.com/laravel/framework) but they have a bunch of subsplits for the various Illuminate subdirectories (https://github.com/illuminate/http for example).

You can see how they used to do this here: 
https://github.com/laravel/framework/blob/5.1/build/illuminate-split.sh

And a post about how it is done here:
https://www.tomasvotruba.cz/blog/2017/01/31/how-monolithic-repository-in-open-source-saved-my-laziness/

Sorry for the snarky comment above, but in my experience complaining about things to Google is about as effective as shouting at a hurricane. If you guys don't mind simply having an extra 150 repositories, the extra build legwork by you guys could save everyone who uses this repository roughly ~15-30 seconds per `composer update` (depending on machine specs).

**Comment by janhartigan** [comment]
More information here about subsplit: https://github.com/dflydev/git-subsplit

**Comment by highstrike** [comment]
Would really like to see an update on this.
My composer has to download 7000+ files just for this code here:
```
// verify validity of token
$client = new Google_Client(array_merge(['jwt' => $jwt], $config));
$payload = $client->verifyIdToken($request->getData('id_token'));
if(!$payload)
    return false;
```
This is quite silly and a _MASSIVE_ overkill just like OP wrote.

**Comment by feelsad** [comment]
Full agree with janhartigan

1.  the google api lib is too large , about 16.8M but i just wanna use the simple function
2. the composer update waste much of my time.  Here is China, it`s not ~15-30 seconds per composer update, It waste too many minutes per composer update

**Comment by mattwhisenhunt** [comment]
Thanks everybody for your input. We are moving newer libraries in this direction as seen in the [GCP libraries](https://github.com/GoogleCloudPlatform/google-cloud-php) 

Since it is not a change we are going to make to this repo, I am closing this issue.
