### ISSUE TITLE
enforce coding standards

### ISSUE THREAD

**Issue by frazjp65** [google/google-api-php-client-services#78]
According to the [contributor's guide](https://github.com/google/google-api-php-client-services/blob/master/CONTRIBUTING.md): 

> 3. Ensure that your code adheres to standard PHP conventions, as used in the rest of the library.

We should use phpcs to enforce the coding standards that are used throughout the library.

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.

**Comment by frazjp65** [comment]
That makes sense to me. I closed the pull request.
