### ISSUE TITLE
Duplicate files for service BigQueryDataTransfer

### ISSUE THREAD

**Issue by muratyaman** [google/google-api-php-client-services#85]
```
/src/Google/Service/BIGQUERYDATATRANSFER.php
/src/Google/Service/BigQueryDataTransfer.php
```

One of them (possibly the second one) must be more up-to-date.
If we use the first one, PSR-0 autoloader would fail
(in an OS with case-sensitive file system)
to load some classes (e.g. class Google_Service_BIGQUERYDATATRANSFER_Resource_Projects)
as there is no folder called:

`/src/Google/Service/BIGQUERYDATATRANSFER/`

**Comment by saicheems** [comment]
Fixed.
