### ISSUE TITLE
Calling get() on null in PurchasesProduct

### ISSUE THREAD

**Issue by DaveBamb** [google/google-api-php-client-services#87]
Hi, I'm trying to make a product purchase validation using a service account, here's my PHP code:

        require_once "../path/to/vendor/autoload.php";
	putenv('GOOGLE_APPLICATION_CREDENTIALS=../path/to/ServiceAccountJSONkey');
	
	$packageName = ""; //PackageName
	$productId= "";  //ProductID
	$token = ""; // purchase token

	$client = new Google_Client();
	$client->setScopes(['https://www.googleapis.com/auth/androidpublisher']);
	$client->useApplicationDefaultCredentials();

	if($client->isAccessTokenExpired()) {
		$client->refreshTokenWithAssertion();
	}

	$service = new Google_Service_AndroidPublisher($client);
	$results = $service->products->get($packageName, $productId, $token, array());
	
	exit; 

But I'm getting this error: 

> Fatal error: Call to a member function get() on null in ../purchaseValidation.php on line X

Where X is this line: `$results = $service->products->get($packageName, $productId, $token, array());`

I don't know what I'm doing wrong, I tried to look for examples on the net but no luck.
Any help would be appreciated, thank you!

**Comment by DaveBamb** [comment]
Ok, after several trial and error you need to call `$service->purchases_products->get(...)` instead of `$service->products->get(...)` as stated in the source code like in: https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/AndroidPublisher/Resource/PurchasesProducts.php where the usage example is wrong.

Now the returned result doesn't have an 'orderID' field like it's supposed to have as stated in here: 
https://developers.google.com/android-publisher/api-ref/purchases/products

I tested it with a testing purchase (purchase with a test google account that doesn't charge money), maybe it's because of that?

**Comment by mattwhisenhunt** [comment]
Sorry this slipped through the cracks and went unanswered for so long. Could you try testing this on [API Explorer](https://developers.google.com/apis-explorer/#p/androidpublisher/v2/) to see if the orderID shows up there?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
