### ISSUE TITLE
get all items / id from the warning list

### ISSUE THREAD

**Issue by johnraypaulin14** [google/google-api-php-client-services#89]
Hi,

I've read through the code especially the part for datafeeds. I'm just wondering if if is possible to get the items in the warning list? Perhaps like the code, the message and id of the product?

**Comment by mattwhisenhunt** [comment]
Hi John,

It sounds like the class Google_Service_ShoppingContent_DatafeedStatus may
be what you are looking for.
Check out
https://developers.google.com/apis-explorer/#search/content/content/v2/ to
be sure, it will help send API queries and show you what information
responses contain. It can be quite a bit faster than getting something
going programmatically in PHP.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We didn't see any follow up in over a week so we are closing it. Please feel free to re-open this issue with more information.

**Comment by johnraypaulin14** [comment]
hi mattwhisenhunt

It turned out that what I really wanted is the product statuses. My problem now is how to paginate the results. Basically, I want create pagination of the results. For now, I can get a 25-result page that comes with a token for a next page. Is it possible to create pagination on this? Or do I have to get all product statuses first before working on pagination?
