### ISSUE TITLE
how to paginate product or product statuses result?

### ISSUE THREAD

**Issue by johnraypaulin14** [google/google-api-php-client-services#91]
What I want is to get the product statuses. My problem now is how to paginate the results. Basically, I want create pagination of the results. For now, I can get a 25-result page that comes with a token for a next page. Is it possible to create pagination on this? Or do I have to get all product statuses first before working on pagination?

` $statuses = $service->productstatuses->listProductstatuses('id', $parameters);`

**Comment by mattwhisenhunt** [comment]
I am not very familiar with Content API for Shopping. After glancing at the reference I would suggest that: you might want to initially page completely through the list method to have a complete collection of all statuses and from then on out maintain a list of productIds to get update for and retrieve those updates with [custombatch](https://developers.google.com/shopping-content/v2/reference/v2/productstatuses/custombatch)

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
