### ISSUE TITLE
Google Fitness Bad Request

### ISSUE THREAD

**Issue by fafabone** [google/google-api-php-client-services#99]
I'm able to authenticate, to get datasources, but I'm not able to aggregate datasets.

Here my code:

$fitness = new Google_Service_Fitness($client);
$datasets = $fitness->users_dataset;
$aggBy = new Google_Service_Fitness_AggregateBy();
$bucketBy = new Google_Service_Fitness_BucketByTime();
$aggBy->setDataTypeName("com.google.step_count.delta");
$bucketBy->setDurationMillis("86400000");
$aggReq = new Google_Service_Fitness_AggregateRequest();
$aggReq->startTimeMillis = strtotime("-2 year");
$aggReq->endTimeMillis = time();
$aggReq->setAggregateBy($aggBy);
$aggReq->setBucketByTime($bucketBy);
$aggregates = $datasets->aggregate('me',$aggReq);

and here the exception generated by google service asnwer:

Message: { "error": { "errors": [ { "domain": "global", "reason": "invalidArgument", "message": "Require at least one aggregateby" } ], "code": 400, "message": "Require at least one aggregateby" } }
Code: 400
File: C:\wamp64\www\libs\google-api-php-client-2.2.0\src\Google\Http\REST.php

So is a problem of my code or is a problem of the library request?

**Comment by MorozovIvan** [comment]
"$aggReq->setAggregateBy($aggBy); "
Try brackets like $aggReq->setAggregateBy([$aggBy]);

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please add a comment if you have any more questions and we can reopen this issue.
